# Generated by Django 5.2.5 on 2025-11-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_workshop_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshopregistration",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Participant's country",
                max_length=100,
                null=True,
                verbose_name="Country",
            ),
        ),
        migrations.AlterField(
            model_name="workshopregistration",
            name="django_experience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Beginner", "Beginner"),
                    ("Intermediate", "Intermediate"),
                    ("Advanced", "Advanced"),
                ],
                help_text="Optional: Only required for Django-specific workshops",
                max_length=20,
                null=True,
                verbose_name="Django Experience Level",
            ),
        ),
    ]
